feat: grinding
Electron-Labs/fri-commitment pull request #13
Opened 2023-11-24 07:35 UTC by yagnadeepxo

2023-11-24 07:37 UTC, yagnadeepxo commented
[dependencies]
sha3 = "0.10.8"

[[test]]
name = "grinding_test"
path = "src/grinding.rs"


cargo.toml

2023-11-24 13:19 UTC, utsavjnn requested changes

2023-11-24 13:19 UTC, utsavjnn commented on src/grinding.rs
> +    (0..u64::MAX).find(|&test_nonce| {
@yagnadeepxo can you do it parallely? Not the best idea to go from `0 to u64::MAX` sequentially.

2023-11-24 13:25 UTC, utsavjnn commented
Also would be great if you could make it part of the fri config, and integrate it in the actuall proof generation and verification process.

2023-11-25 06:40 UTC, yagnadeepxo commented on src/grinding.rs
> +    (0..u64::MAX).find(|&test_nonce| {
added with rayon

2023-11-29 06:45 UTC, yagnadeepxo commented
added grinding to FRIConfig @utsavjnn

2023-11-30 12:01 UTC, closed without merging